### ISSUE TITLE
Core dump when creating Tilt Series Settings File following the tutorial

### ISSUE THREAD

**Issue by estrella-sbgrid** [warpem/warp#120]
Hi,

I am Estrella from SBGrid, we have recently add Warp for Linux to our SBGrid collection. However, during the testing using the tutorial (https://warpem.github.io/warp/user_guide/warptools/quick_start_warptools_tilt_series/), I got a "core dump" when executing this command:
```
WarpTools create_settings \
--output warp_tiltseries.settings \
--folder_processing warp_tiltseries \
--folder_data tomostar \
--extension "*.tomostar" \
--angpix 0.7894 \
--gain_path gain_ref.mrc \
--gain_flip_y \
--exposure 2.64 \
--tomo_dimensions 4400x6000x1000
```
The complete error message that I got is:
```
Unhandled exception. System.IO.DirectoryNotFoundException: Could not find a part of the path '/nfs/builders/sbtest/Downloads/warp_estrella/tomostar'.
  at [System.IO](http://system.io/).Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
  at [System.IO](http://system.io/).Enumeration.FileSystemEnumerator`1.Init()
  at [System.IO](http://system.io/).Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
  at [System.IO](http://system.io/).Enumeration.FileSystemEnumerableFactory.UserFiles(String directory, String expression, EnumerationOptions options)
  at [System.IO](http://system.io/).Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
  at WarpTools.Commands.CreateSettings.Run(Object options) in /usr/share/miniconda/envs/package-build/conda-bld/warp_1717046947634/work/WarpTools/Commands/CreateSettings.cs:line 232
  at WarpTools.WarpTools.Run(Object options) in /usr/share/miniconda/envs/package-build/conda-bld/warp_1717046947634/work/WarpTools/Program.cs:line 30
  at Warp.Tools.CommandLineParserHelper.ParseAndRun(String[] args, Func`2 run, Type[] verbs, String appName) in /usr/share/miniconda/envs/package-build/conda-bld/warp_1717046947634/work/WarpLib/Tools/CommandLineParserHelper.cs:line 26
  at WarpTools.WarpTools.Main(String[] args) in /usr/share/miniconda/envs/package-build/conda-bld/warp_1717046947634/work/WarpTools/Program.cs:line 17
  at WarpTools.WarpTools.<Main>(String[] args)
/programs/share/capsules/lib/job.sh: line 126: 14592 Aborted         (core dumped) "$SB_EXECFILE" "$@"
```

I guessed it is produced just because _tomostar_ dir is not already created (it is generated two steps later when importing Tilt Series Metadata).  So I guess it is not really a problem, as then everything works fine, however the error message is quite alarming for the user... I would suggest to change the error handling to give just a warning "tomostar dir is not already created" or just warn the user in the tutorial to create manually tomostar directory. 

On the other hand, when downloading the data at the beginning of the tutorial, it complains about _wget_ option `--show-progress`. I think it is not available in some versions of wget, however, I read that wget is using the `--verbose` option by default, thus maybe you can remove the `--show-progress` option from the tutorial just to avoid the user getting this error.

Hope it helps. BTW, Warp is already available and running in SBGrid :)

Best,
Estrella

**Comment by alisterburt** [comment]
Hi @estrella-sbgrid - thanks for the report! I had been meaning to do something about that core dump, you're right that it's not actually a problem 🙂

Will also remove wget from the tutorial
