### ISSUE TITLE
no warptool to prepare data for 2D boxnet training

### ISSUE THREAD

**Issue by alisterburt** [warpem/warp#14]
discussed in #8 - we need to add a WarpTool which prepares data for boxnet training

@cdienem the workaround for the lack of this tool right now is to prepare for training in the Desktop GUI - you can cancel after data are prepared then finish training with WarpTools

**Comment by simonecavadini** [comment]
Hi All,
thanks for your suggestions. I understand that the models trained with Warp 1.0 are not suitable for picking particles using WarTools, so I was wondering if there are any news regarding re-training a BoxNet model using fs_boxnet_train. I tried your suggestions above and I created a new tif file using Warp GUI in Windows. This is now saved in the folder boxnet2training. 

This is what I run and get:

 WarpTools fs_boxnet_train --model_in ../BoxNet2_20180602/saved_model.pb --model_out new_weights --examples boxnet2training/
Running command fs_boxnet_train with:
model_in = ../BoxNet2_20180602/saved_model.pb
model_out = new_weights
examples = boxnet2training/
examples_general = null
no_mask = False
patchsize = 512
batchsize = 8
lr_start = 5E-05
lr_end = 1E-05
epochs = 100
checkpoints = 0
devices = {  }

Loading data...boxnet2training/BoxNet2Mask_forlinux2.tif
Unhandled exception. System.Exception: All zeros
   at WarpTools.Commands.BoxNetTrainFrameseries.Run(Object options) in /usr/share/miniconda/envs/package-build/conda-bld/warp_1727282134776/work/WarpTools/Commands/Frameseries/BoxNetTrainFrameseries.cs:line 179
   at WarpTools.WarpTools.Run(Object options) in /usr/share/miniconda/envs/package-build/conda-bld/warp_1727282134776/work/WarpTools/Program.cs:line 30
   at Warp.Tools.CommandLineParserHelper.ParseAndRun(String[] args, Func`2 run, Type[] verbs, String appName) in /usr/share/miniconda/envs/package-build/conda-bld/warp_1727282134776/work/WarpLib/Tools/CommandLineParserHelper.cs:line 26
   at WarpTools.WarpTools.Main(String[] args) in /usr/share/miniconda/envs/package-build/conda-bld/warp_1727282134776/work/WarpTools/Program.cs:line 17
   at WarpTools.WarpTools.<Main>(String[] args)
Aborted

Thank you so much in advance for your support! Looking forward to your reply. Best, Simone

**Comment by alisterburt** [comment]
@simonecavadini @tegunovd got excited about making BoxNet multimodal (combining picking and denoising). This should give better performance for new data in the future. I'm actually not sure on the current state of that work so will defer to Dimitry...

**Comment by simonecavadini** [comment]
@alisterburt thanks a lot for your quick reply. I also tried to export the "examples" TIF using the Desktop GUI 1.1 beta starting from boxnet3. I get the same error:

Loading data...boxnet3training/BoxNet_20220403_191253_2.tif
Unhandled exception. System.Exception: All zeros

Any idea what "All zeros" refers to? Please let me know if you have any other idea on how to use WarpTools to pick particles for single-particle. I am afraid that without a proper model trained with WarpTools fs_boxnet_train this is not going to work. 

Thanks, Simone

**Comment by dtegunov** [comment]
Sorry, BoxNet is currently stuck in limbo. Unfortunately, we're busy with a different software emergency until the end of the year. This is at the top of our to-do list for next year.

**Comment by simonecavadini** [comment]
@dtegunov thanks for the feedback, looking forward to the new year;-) Best, S
