### ISSUE TITLE
Locale issues when creating settings

### ISSUE THREAD

**Issue by alisterburt** [warpem/warp#146]
Reported by @RamteenS

> I noticed by the way that, at the beginning of the processing when creating settings files, i need to put coma for the pixel size otherwise it does not create the settings file:

**Comment by alisterburt** [comment]
I can't see any remaining `float.Parse()` calls which do not have `CultureInfo.InvariantCulture` specified so I can't see why your settings creation would fail. @RamteenS could you paste the traceback?

```py
In [9]: for f in files:
   ...:     print(f'looking at {f}')
   ...:     f = open(f, mode='r')
   ...:     lines = f.readlines()
   ...:     for idx, line in enumerate(lines):
   ...:         if ('float.Parse' in line) and not ('CultureInfo.InvariantCulture' in line):
   ...:             print(f'{idx}: {line}')
   ...:     f.close()

```

```txt
looking at MrcConverter/Options.cs
looking at MrcConverter/MrcConverter.cs
looking at MrcConverter/obj/Debug/.NETCoreApp,Version=v8.0.AssemblyAttributes.cs
looking at MrcConverter/obj/Debug/MrcConverter.AssemblyInfo.cs
looking at Noise2Half/Noise2Half.cs
looking at Noise2Half/obj/Debug/.NETCoreApp,Version=v8.0.AssemblyAttributes.cs
looking at Noise2Half/obj/Debug/Noise2Half.AssemblyInfo.cs
looking at WarpWorker/REST.cs
looking at WarpWorker/OptionsCLI.cs
looking at WarpWorker/WarpWorker.cs
looking at WarpWorker/obj/Debug/.NETCoreApp,Version=v8.0.AssemblyAttributes.cs
looking at WarpWorker/obj/Debug/WarpWorker.AssemblyInfo.cs
looking at WarpWorker/API/Service.cs
looking at WarpWorker/API/Console.cs
looking at MCore/OptionsCLI.cs
looking at MCore/MCore.cs
looking at MCore/obj/Debug/.NETCoreApp,Version=v8.0.AssemblyAttributes.cs
looking at MCore/obj/Debug/MCore.AssemblyInfo.cs
looking at Noise2Map/Options.cs
looking at Noise2Map/Noise2Map.cs
looking at Noise2Map/obj/Debug/.NETCoreApp,Version=v8.0.AssemblyAttributes.cs
looking at Noise2Map/obj/Debug/Noise2Map.AssemblyInfo.cs
looking at WarpLib/TiltSeries.cs
looking at WarpLib/WorkerWrapper.cs
looking at WarpLib/CPU.cs
looking at WarpLib/Star.cs
779:             return (name1 == null ? GetColumn(0) : GetColumn(name1)).Select(v => float.Parse(v.Replace("inf", "Infinity").

looking at WarpLib/OptionsWarp.cs
looking at WarpLib/SoftMap.cs
looking at WarpLib/LinearGrid4D.cs
looking at WarpLib/Cubic1D.cs
looking at WarpLib/CTF.cs
looking at WarpLib/WarpBase.cs
looking at WarpLib/GPU.cs
looking at WarpLib/FFTW.cs
looking at WarpLib/ProcessingOptions.cs
looking at WarpLib/Image.cs
looking at WarpLib/CubicGrid.cs
looking at WarpLib/Cubic1DShort.cs
looking at WarpLib/Projector.cs
looking at WarpLib/NMAMap.cs
201:                             float3 AtomPos = new float3(float.Parse(Line.Substring(30, 8)),

202:                                                         float.Parse(Line.Substring(38, 8)),

203:                                                         float.Parse(Line.Substring(46, 8))) / pixelSize;

looking at WarpLib/Movie.cs
looking at WarpLib/FSC.cs
looking at WarpLib/obj/Debug/.NETCoreApp,Version=v8.0.AssemblyAttributes.cs
looking at WarpLib/obj/Debug/WarpLib.AssemblyInfo.cs
looking at WarpLib/NNModels/C2DNet.cs
looking at WarpLib/NNModels/TomoNet.cs
looking at WarpLib/NNModels/TildeNet.cs
looking at WarpLib/NNModels/DistanceNet.cs
looking at WarpLib/NNModels/CubeNetTorch.cs
looking at WarpLib/NNModels/NoiseNet3DTorch.cs
looking at WarpLib/NNModels/NoiseNet2DTorch.cs
looking at WarpLib/NNModels/ParticleWGAN.cs
looking at WarpLib/NNModels/BoxNetTorch.cs
looking at WarpLib/Tools/ImageHelper.cs
looking at WarpLib/Tools/Matrix3.cs
looking at WarpLib/Tools/Quaternion.cs
looking at WarpLib/Tools/ClusterTrieste.cs
looking at WarpLib/Tools/Logger.cs
looking at WarpLib/Tools/CommandLineParserHelper.cs
looking at WarpLib/Tools/MathHelper.cs
looking at WarpLib/Tools/Matrix2.cs
looking at WarpLib/Tools/TiffNative.cs
looking at WarpLib/Tools/EERNative.cs
looking at WarpLib/Tools/Symmetry.cs
looking at WarpLib/Tools/ColorScale.cs
looking at WarpLib/Tools/IntVectors.cs
looking at WarpLib/Tools/BenchmarkTimer.cs
looking at WarpLib/Tools/Zernike.cs
looking at WarpLib/Tools/HungarianAlgorithm.cs
looking at WarpLib/Tools/GlobalTasks.cs
looking at WarpLib/Tools/DefectModel.cs
looking at WarpLib/Tools/MallocCache.cs
looking at WarpLib/Tools/ByteReaderBE.cs
looking at WarpLib/Tools/ImodHelper.cs
looking at WarpLib/Tools/XMLHelper.cs
looking at WarpLib/Tools/FFTPlanCache.cs
looking at WarpLib/Tools/IOHelper.cs
looking at WarpLib/Tools/FloatVectors.cs
looking at WarpLib/Tools/SplinePath1D.cs
looking at WarpLib/Tools/RandomNormal.cs
looking at WarpLib/Tools/SplinePath2D.cs
looking at WarpLib/Tools/Timing.cs
looking at WarpLib/Tools/VirtualConsole.cs
looking at WarpLib/Tools/Helper.cs
looking at WarpLib/Tools/Spandex.cs
looking at WarpLib/Tools/PhysicsHelper.cs
805:                         float3 AtomPos = new float3(float.Parse(Line.Substring(30, 8)),

806:                                                     float.Parse(Line.Substring(38, 8)),

807:                                                     float.Parse(Line.Substring(46, 8)));

looking at WarpLib/Tools/NamedSerializableObject.cs
looking at WarpLib/Tools/Matrix4.cs
looking at WarpLib/Sociology/Population.cs
looking at WarpLib/Sociology/Species.cs
looking at WarpLib/Sociology/DataSource.cs
looking at WarpLib/Sociology/Particle.cs
looking at WarpLib/Headers/EM.cs
looking at WarpLib/Headers/Tiff.cs
looking at WarpLib/Headers/Raw.cs
looking at WarpLib/Headers/MRC.cs
looking at WarpLib/Headers/Headers.cs
looking at WarpLib/Headers/EER.cs
looking at WarpLib/Headers/DM4.cs
looking at WarpTools/Program.cs
looking at WarpTools/obj/Debug/.NETCoreApp,Version=v8.0.AssemblyAttributes.cs
looking at WarpTools/obj/Debug/WarpTools.AssemblyInfo.cs
looking at WarpTools/Commands/DistributedOptions.cs
looking at WarpTools/Commands/HelpGPT.cs
looking at WarpTools/Commands/BaseCommand.cs
looking at WarpTools/Commands/BaseOptions.cs
looking at WarpTools/Commands/CreateSettings.cs
looking at WarpTools/Commands/General/ThresholdPicks.cs
looking at WarpTools/Commands/General/MoveData.cs
looking at WarpTools/Commands/General/ChangeSelection.cs
looking at WarpTools/Commands/General/FilterQuality.cs
looking at WarpTools/Commands/Tiltseries/EtomoPatchTrackTiltseries.cs
looking at WarpTools/Commands/Tiltseries/AreTomoTiltseries.cs
looking at WarpTools/Commands/Tiltseries/DefocusHandTiltseries.cs
looking at WarpTools/Commands/Tiltseries/EtomoFiducialsTiltseries.cs
looking at WarpTools/Commands/Tiltseries/StackTiltseries.cs
looking at WarpTools/Commands/Tiltseries/ReconstructTiltseries.cs
looking at WarpTools/Commands/Tiltseries/ImportAlignmentsTiltseries.cs
looking at WarpTools/Commands/Tiltseries/ImportTiltseries.cs
looking at WarpTools/Commands/Tiltseries/CTFTiltseries.cs
looking at WarpTools/Commands/Tiltseries/ExportParticlesTiltseries.cs
looking at WarpTools/Commands/Tiltseries/EvaluateModelTiltseries.cs
looking at WarpTools/Commands/Tiltseries/AlignTiltseries.cs
looking at WarpTools/Commands/Tiltseries/TemplateMatchTiltseries.cs
looking at WarpTools/Commands/Frameseries/CTFFrameseries.cs
looking at WarpTools/Commands/Frameseries/ExportMicrographsFrameseries.cs
looking at WarpTools/Commands/Frameseries/BoxNetInferFrameseries.cs
looking at WarpTools/Commands/Frameseries/ExportParticlesFrameseries.cs
looking at WarpTools/Commands/Frameseries/MotionFrameseries.cs
looking at WarpTools/Commands/Frameseries/MotionCTFFrameseries.cs
looking at WarpTools/Commands/Frameseries/BoxNetTrainFrameseries.cs
looking at PCA3D/Options.cs
looking at PCA3D/PCA3D.cs
looking at PCA3D/obj/Debug/.NETCoreApp,Version=v8.0.AssemblyAttributes.cs
looking at PCA3D/obj/Debug/PCA3D.AssemblyInfo.cs
looking at Testing/Program.cs
looking at Testing/obj/Debug/net8.0/Testing.GlobalUsings.g.cs
looking at Testing/obj/Debug/net8.0/.NETCoreApp,Version=v8.0.AssemblyAttributes.cs
looking at Testing/obj/Debug/net8.0/Testing.AssemblyInfo.cs
looking at Noise2Mic/Options.cs
looking at Noise2Mic/Noise2Mic.cs
looking at Noise2Mic/obj/Debug/.NETCoreApp,Version=v8.0.AssemblyAttributes.cs
looking at Noise2Mic/obj/Debug/Noise2Mic.AssemblyInfo.cs
looking at Warp/App.xaml.cs
looking at Warp/MainWindow.xaml.cs
looking at Warp/WebAPI.cs
looking at Warp/FileDiscoverer.cs
looking at Warp/MdocDiscoverer.cs
looking at Warp/GlobalOptions.cs
looking at Warp/obj/Debug/.NETCoreApp,Version=v8.0.AssemblyAttributes.cs
looking at Warp/obj/Debug/Warp_Content.g.cs
looking at Warp/obj/Debug/GeneratedInternalTypeHelper.g.cs
looking at Warp/obj/Debug/Warp.AssemblyInfo.cs
looking at Warp/obj/Debug/Controls/ProgressIndicators/ReconstructionMiniature.g.cs
looking at Warp/obj/Debug/Controls/ProgressIndicators/FlatGridMiniature.g.cs
looking at Warp/obj/Debug/Controls/TaskDialogs/Tomo/DialogTomoList.g.cs
looking at Warp/obj/Debug/Controls/TaskDialogs/2D/Dialog2DList.g.cs
looking at Warp/obj/Debug/Controls/MainUI/StatusBarRow.g.cs
looking at Warp/obj/Debug/Controls/MainUI/StatusBar.g.cs
looking at Warp/obj/Debug/Controls/MainUI/DualAxisScatter.g.cs
looking at Warp/obj/Debug/Controls/MainUI/LogMessageGroup.g.cs
looking at Warp/obj/Debug/Controls/MainUI/LogMessageDisplay.g.cs
looking at Warp/obj/Debug/Controls/MainUI/FirstRunPrompt.g.cs
looking at Warp/obj/Debug/Controls/MainUI/TiltDialItem.g.cs
looking at Warp/obj/Debug/Controls/MainUI/GridMiniature.g.cs
looking at Warp/obj/Debug/Controls/MainUI/SingleAxisScatter.g.cs
looking at Warp/obj/Debug/Controls/BoxNet/BoxNetSelect.g.cs
looking at Warp/Controls/ProgressIndicators/ReconstructionMiniature.xaml.cs
looking at Warp/Controls/ProgressIndicators/FlatGridMiniature.xaml.cs
looking at Warp/Controls/TaskDialogs/Tomo/DialogTomoList.xaml.cs
looking at Warp/Controls/TaskDialogs/Tomo/DialogTomoMatch.xaml.cs
looking at Warp/Controls/TaskDialogs/Tomo/DialogTomoReconstruction.xaml.cs
looking at Warp/Controls/TaskDialogs/Tomo/DialogTomoParticleExport.xaml.cs
looking at Warp/Controls/TaskDialogs/Tomo/DialogTomoImportImod.xaml.cs
looking at Warp/Controls/TaskDialogs/2D/Dialog2DDefocusUpdate.xaml.cs
looking at Warp/Controls/TaskDialogs/2D/Dialog2DList.xaml.cs
looking at Warp/Controls/TaskDialogs/2D/Dialog2DMatch.xaml.cs
looking at Warp/Controls/TaskDialogs/2D/Dialog2DParticleExport.xaml.cs
looking at Warp/Controls/TaskDialogs/2D/Dialog2DParticleImport.xaml.cs
105:                     TableIn.ModifyAllValuesInColumn("rlnCoordinateX", (v, r) => (float.Parse(v) * ScaleFactorCoords - float.Parse(TableIn.GetRowValue(r, IndexOriginX)) * ScaleFactorShifts).ToString("F4"));

110:                     TableIn.ModifyAllValuesInColumn("rlnCoordinateX", v => (float.Parse(v) * ScaleFactorCoords).ToString("F4"));

115:                     TableIn.ModifyAllValuesInColumn("rlnCoordinateY", (v, r) => (float.Parse(v) * ScaleFactorCoords - float.Parse(TableIn.GetRowValue(r, IndexOriginY)) * ScaleFactorShifts).ToString("F4"));

120:                     TableIn.ModifyAllValuesInColumn("rlnCoordinateY", v => (float.Parse(v) * ScaleFactorCoords).ToString("F4"));

142:                             float CoordX = float.Parse(row[IndexCoordX]);

146:                             float CoordY = float.Parse(row[IndexCoordY]);

looking at Warp/Controls/MainUI/FirstRunPrompt.xaml.cs
looking at Warp/Controls/MainUI/DualAxisScatter.xaml.cs
looking at Warp/Controls/MainUI/TiltDialItem.xaml.cs
looking at Warp/Controls/MainUI/LogMessageGroup.xaml.cs
looking at Warp/Controls/MainUI/StatusBar.xaml.cs
looking at Warp/Controls/MainUI/SingleAxisScatter.xaml.cs
looking at Warp/Controls/MainUI/StatusBarRow.xaml.cs
looking at Warp/Controls/MainUI/CTFDisplay.xaml.cs
looking at Warp/Controls/MainUI/GridMiniature.xaml.cs
looking at Warp/Controls/MainUI/MicrographDisplay.xaml.cs
looking at Warp/Controls/MainUI/LogMessageDisplay.xaml.cs
looking at Warp/Controls/BoxNet/BoxNetTrain.xaml.cs
looking at Warp/Controls/BoxNet/BoxNetSelect.xaml.cs
looking at Warp/Controls/BoxNet/BoxNetExport.xaml.cs
looking at Frankenmap/Options.cs
looking at Frankenmap/Frankenmap.cs
looking at Frankenmap/obj/Debug/.NETCoreApp,Version=v8.0.AssemblyAttributes.cs
looking at Frankenmap/obj/Debug/Frankenmap.AssemblyInfo.cs
looking at EstimateWeights/EstimateWeights.cs
looking at EstimateWeights/Options.cs
looking at EstimateWeights/obj/Debug/.NETCoreApp,Version=v8.0.AssemblyAttributes.cs
looking at EstimateWeights/obj/Debug/EstimateWeights.AssemblyInfo.cs
looking at TorchSharp/TorchScalar.cs
looking at TorchSharp/PinnedArray.cs
looking at TorchSharp/Torch.cs
looking at TorchSharp/Autograd.cs
looking at TorchSharp/ExtensionMethods.cs
looking at TorchSharp/obj/Debug/.NETCoreApp,Version=v8.0.AssemblyAttributes.cs
looking at TorchSharp/obj/Debug/TorchSharp.AssemblyInfo.cs
looking at TorchSharp/NN/C2DNet.cs
looking at TorchSharp/NN/Linear.cs
looking at TorchSharp/NN/BatchNorm2D.cs
looking at TorchSharp/NN/LeakyReLU.cs
looking at TorchSharp/NN/AvgPool2D.cs
looking at TorchSharp/NN/LogSoftMax.cs
looking at TorchSharp/NN/MaxPool2D.cs
looking at TorchSharp/NN/MLP.cs
looking at TorchSharp/NN/AdaptiveAvgPool2D.cs
looking at TorchSharp/NN/UNet2D.cs
looking at TorchSharp/NN/UNet3D.cs
looking at TorchSharp/NN/DistanceNet.cs
looking at TorchSharp/NN/Module.cs
looking at TorchSharp/NN/Dropout.cs
looking at TorchSharp/NN/Losses.cs
looking at TorchSharp/NN/Init.cs
looking at TorchSharp/NN/Parameter.cs
looking at TorchSharp/NN/ParticleWGAN.cs
looking at TorchSharp/NN/FeatureDropout.cs
looking at TorchSharp/NN/Sequential.cs
looking at TorchSharp/NN/Conv2D.cs
looking at TorchSharp/NN/ResNet.cs
looking at TorchSharp/NN/Discriminator3D.cs
looking at TorchSharp/NN/ReLu.cs
looking at TorchSharp/NN/Optimizer.cs
looking at TorchSharp/JIT/Module.cs
looking at TorchSharp/JIT/Type/TensorType.cs
looking at TorchSharp/JIT/Type/DynamicType .cs
looking at TorchSharp/JIT/Type/Type.cs
looking at TorchSharp/Tensor/TorchTensor.cs
looking at TorchSharp/Tensor/TorchTensorTyped.generated.cs
looking at TorchSharp/Data/Loader.cs
looking at TorchSharp/Data/DataIterator.cs
looking at WarpControls/ValueSlider.xaml.cs
looking at WarpControls/EditableTextBlock.xaml.cs
looking at WarpControls/FormattedTextBlock.xaml.cs
looking at WarpControls/Converters.cs
looking at WarpControls/SingleSliceRenderer.xaml.cs
looking at WarpControls/SymmetrySelector.xaml.cs
looking at WarpControls/VolumeRenderer.xaml.cs
looking at WarpControls/DropMenu.xaml.cs
looking at WarpControls/MultiSliceRenderer.xaml.cs
looking at WarpControls/ProgressIndicators/NyanBar.xaml.cs
looking at WarpControls/ProgressIndicators/OldschoolBar.xaml.cs
looking at WarpControls/obj/Debug/.NETCoreApp,Version=v8.0.AssemblyAttributes.cs
looking at WarpControls/obj/Debug/ValueSlider.g.cs
looking at WarpControls/obj/Debug/EditableTextBlock.g.cs
looking at WarpControls/obj/Debug/VolumeRenderer.g.cs
looking at WarpControls/obj/Debug/SymmetrySelector.g.cs
looking at WarpControls/obj/Debug/FormattedTextBlock.g.cs
looking at WarpControls/obj/Debug/SingleSliceRenderer.g.cs
looking at WarpControls/obj/Debug/DropMenu.g.cs
looking at WarpControls/obj/Debug/MultiSliceRenderer.g.cs
looking at WarpControls/obj/Debug/WarpControls.AssemblyInfo.cs
looking at WarpControls/obj/Debug/GeneratedInternalTypeHelper.g.cs
looking at WarpControls/obj/Debug/ProgressIndicators/OldschoolBar.g.cs
looking at WarpControls/obj/Debug/ProgressIndicators/NyanBar.g.cs
looking at M/App.xaml.cs
looking at M/MainWindow.xaml.cs
looking at M/Options.cs
looking at M/obj/Debug/.NETCoreApp,Version=v8.0.AssemblyAttributes.cs
looking at M/obj/Debug/MainWindow.g.cs
looking at M/obj/Debug/M_Content.g.cs
looking at M/obj/Debug/M.AssemblyInfo.cs
looking at M/obj/Debug/Controls/Sociology/Dialogs/DialogAddSpecies.g.cs
looking at M/obj/Debug/Controls/Sociology/Dialogs/DialogDataSources.g.cs
looking at M/Controls/DialogRefinementSettings.xaml.cs
looking at M/Controls/Sociology/SpeciesView.xaml.cs
looking at M/Controls/Sociology/Dialogs/DialogSpeciesRotate.xaml.cs
looking at M/Controls/Sociology/Dialogs/DialogCreateNewSpecies.xaml.cs
looking at M/Controls/Sociology/Dialogs/DialogAddSpecies.xaml.cs
looking at M/Controls/Sociology/Dialogs/DialogTomoParticleExport.xaml.cs
looking at M/Controls/Sociology/Dialogs/DialogSpeciesParticleSets.xaml.cs
looking at M/Controls/Sociology/Dialogs/DialogSpeciesShift.xaml.cs
looking at M/Controls/Sociology/Dialogs/DialogDataSources.xaml.cs
looking at M/Controls/Sociology/Dialogs/DialogSpeciesSymExpand.xaml.cs
looking at M/Controls/Sociology/Dialogs/DialogCreatePopulation.xaml.cs
looking at M/Controls/Sociology/Dialogs/DialogCreateSourceFromSettings.xaml.cs
looking at Noise2Tomo/Options.cs
looking at Noise2Tomo/Noise2Tomo.cs
looking at Noise2Tomo/Noise2Tomo_randomangles.cs
looking at Noise2Tomo/obj/Debug/.NETCoreApp,Version=v8.0.AssemblyAttributes.cs
looking at Noise2Tomo/obj/Debug/Noise2Tomo.AssemblyInfo.cs
looking at MTools/MTools.cs
looking at MTools/obj/Debug/.NETCoreApp,Version=v8.0.AssemblyAttributes.cs
looking at MTools/obj/Debug/MTools.AssemblyInfo.cs
looking at MTools/Commands/ListSpecies.cs
looking at MTools/Commands/ResampleParticleTrajectories.cs
looking at MTools/Commands/RemoveSpecies.cs
looking at MTools/Commands/UpdateMask.cs
looking at MTools/Commands/CreatePopulation.cs
looking at MTools/Commands/CreateSpecies.cs
414:                         float DetectorPixel = float.Parse(TableRelion.GetRowValue(0, "rlnDetectorPixelSize")) * 1e4f;

415:                         float Mag = float.Parse(TableRelion.GetRowValue(0, "rlnMagnification"));

428:                     AngPixCoords = float.Parse(TableRelion.GetRowValue(0, "rlnImagePixelSize"));

432:                     AngPixCoords = float.Parse(TableOptics.GetRowValue(0, "rlnImagePixelSize"));

looking at MTools/Commands/ShiftSpecies.cs
looking at MTools/Commands/AddSource.cs
looking at MTools/Commands/ListSources.cs
looking at MTools/Commands/BaseCommand.cs
looking at MTools/Commands/CreateSource.cs
looking at MTools/Commands/RotateSpecies.cs
looking at MTools/Commands/RemoveSource.cs
looking at MTools/Commands/ExpandSymmetry.cs

```

**Comment by RamteenS** [comment]
Hi Alister,
When creating the settings files (same for both frameseries and tiltseries) i get the following core dump error if i put a dot  instead of coma for the pixel size: 
(warp) [ramteen@022-031-LNX Warp_M]$ WarpTools create_settings \
> --folder_data frames \
> --folder_processing warp_frameseries \
> --output warp_frameseries.settings \
> --extension "*.tif" \
> --angpix 0.7894 \
> --gain_path gain_ref.mrc \
> --gain_flip_y \
> --exposure 2.64
Running command create_settings with:
output = warp_frameseries.settings
folder_processing = warp_frameseries
folder_data = frames
recursive = False
extension = *.tif
angpix = 0.7894
bin = null
bin_angpix = null
gain_path = gain_ref.mrc
defects_path = null
gain_flip_x = False
gain_flip_y = True
gain_transpose = False
exposure = 2,64
eer_ngroups = 40
eer_groupexposure = null
tomo_dimensions = null

Pixel size is not a number, trying to read from file instead...
Unhandled exception. System.Exception: No files found matching 0.7894
   at WarpTools.Commands.CreateSettings.Run(Object options) in /usr/share/miniconda/envs/package-build/conda-bld/warp_1718315900454/work/WarpTools/Commands/CreateSettings.cs:line 117
   at WarpTools.WarpTools.Run(Object options) in /usr/share/miniconda/envs/package-build/conda-bld/warp_1718315900454/work/WarpTools/Program.cs:line 30
   at Warp.Tools.CommandLineParserHelper.ParseAndRun(String[] args, Func`2 run, Type[] verbs, String appName) in /usr/share/miniconda/envs/package-build/conda-bld/warp_1718315900454/work/WarpLib/Tools/CommandLineParserHelper.cs:line 26
   at WarpTools.WarpTools.Main(String[] args) in /usr/share/miniconda/envs/package-build/conda-bld/warp_1718315900454/work/WarpTools/Program.cs:line 17
   at WarpTools.WarpTools.<Main>(String[] args)
Aborted (core dumped)

Thanks for your help again 

Best 

Ramteen

**Comment by dtegunov** [comment]
It was hiding in a decimal.Parse rather than float.Parse. I went through the whole solution and fixed all instances of decimal and double parsing. Should be fixed in e237148.

**Comment by alisterburt** [comment]
pushed as `v2.0.0dev14`
https://github.com/warpem/warp/actions/runs/9554134582/job/26334528289

**Comment by RamteenS** [comment]
Thanks a lot, both of you. This issue has been fixed. Nevertheless, I have another problem now during tomogram reconstruction. I will open a new issue!

Thank again 

Best 

Ramteen
