### ISSUE TITLE
ts_ctf does not work with --fit_phase

### ISSUE THREAD

**Issue by Luc1100** [warpem/warp#158]
Hi,

I am trying out Warp on some data collected with a phase plate. When running ctf estimation on frame series with --fit_phase, it works great with the histogram centered around 0.5*pi. However, when I run ts_ctf with --fit_phase option, I get the error below. When running ts_ctf without that option it works fine. Any help would be appreciated, thanks!

Running command ts_ctf with:
window = 512
range_low = 30
range_high = 7
defocus_min = 0.5
defocus_max = 8
voltage = 300
cs = 2.7
amplitude = 0.07
fit_phase = True
auto_hand = 0
device_list = {  }
perdevice = 1
workers = {  }
settings = warp_tiltseries.settings
input_data = {  }
input_data_recursive = False
input_processing = null
output_processing = null

No alternative input specified, will use input parameters from warp_tiltseries.settings
File search will be relative to redacted/WRM_learning/redacted/tomostar
1 files found
Parsing previous results for each item, if available...
1/1, previous metadata found for 1                                                                                                                                     
Connecting to workers...
Connected to 1 workers
Failed to process redacted/WRM_learning/redacted/warp_tiltseries/TS16.tomostar, marked as unselected                                                   
Unhandled exception. System.AggregateException: One or more errors occurred. (Connection refused (localhost:38119))
 ---> System.Net.Http.HttpRequestException: Connection refused (localhost:38119)
 ---> System.Net.Sockets.SocketException (111): Connection refused
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|285_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Warp.WorkerConsole.SetFileOutput(String path) in /usr/share/miniconda/envs/package-build/conda-bld/warp_1718655385920/work/WarpLib/WorkerWrapper.cs:line 541
   at WarpTools.Commands.BaseCommand.<>c__DisplayClass1_0.<IterateOverItems>b__0(Int32 iitem, Int32 threadID) in /usr/share/miniconda/envs/package-build/conda-bld/warp_1718655385920/work/WarpTools/Commands/BaseCommand.cs:line 103
   at Warp.Tools.Helper.ForCPUGreedy(Int32 fromInclusive, Int32 toExclusive, Int32 nThreads, Action`1 funcSetup, Action`2 funcIterator, Action`1 funcTeardown) in /usr/share/miniconda/envs/package-build/conda-bld/warp_1718655385920/work/WarpLib/Tools/Helper.cs:line 786
   at WarpTools.Commands.BaseCommand.IterateOverItems(WorkerWrapper[] workers, BaseOptions cli, Action`2 body, Int32 oversubscribe) in /usr/share/miniconda/envs/package-build/conda-bld/warp_1718655385920/work/WarpTools/Commands/BaseCommand.cs:line 67
   at WarpTools.Commands.CTFTiltseries.Run(Object options) in /usr/share/miniconda/envs/package-build/conda-bld/warp_1718655385920/work/WarpTools/Commands/Tiltseries/CTFTiltseries.cs:line 119
   at WarpTools.WarpTools.Run(Object options) in /usr/share/miniconda/envs/package-build/conda-bld/warp_1718655385920/work/WarpTools/Program.cs:line 30
   at Warp.Tools.CommandLineParserHelper.ParseAndRun(String[] args, Func`2 run, Type[] verbs, String appName) in /usr/share/miniconda/envs/package-build/conda-bld/warp_1718655385920/work/WarpLib/Tools/CommandLineParserHelper.cs:line 26
   at WarpTools.WarpTools.Main(String[] args) in /usr/share/miniconda/envs/package-build/conda-bld/warp_1718655385920/work/WarpTools/Program.cs:line 17
   at WarpTools.WarpTools.<Main>(String[] args)
Aborted (core dumped)

**Comment by alisterburt** [comment]
thanks for the report @Luc1100 ! I'll take a look into it but can't provide guarantees about a speedy resolution 🙂

**Comment by steffen-klein** [comment]
Hi @alisterburt, I have been running into the same issue recently and wonder if there is any news about a possible solution. Thanks a lot! Steffen

**Comment by alisterburt** [comment]
hi @steffen-klein ! No news unfortunately, sorry about that - because VPP data fell out of fashion for the most part it hasn't been high priority although it does look like a few people are trying to process this data right now...

I assume you're pushing this because of Joe's data showing better initial results with VPP data?

**Comment by steffen-klein** [comment]
Hi @alisterburt, Here in the Mahamid Lab, we have several projects that use VPP (e.g., whenever the highest resolution is not essential but cellular features are more relevant). For this data, we currently use warp on Windows. As we are now switching to warp2 , I wanted to sync the data processing pipeline for all data and thus also use warp2 on VPP tomograms. Implementing this feature would certainly be highly appreciated by many.

**Comment by alisterburt** [comment]
@steffen-klein thanks for the perspective!

**Comment by alisterburt** [comment]
@steffen-klein it looks like per tilt defocus will come from the 2d results stored in `GridCTFDefocus`

https://github.com/warpem/warp/blob/437508855b2a1c26858bc191d110fa3ad6b656cf/WarpLib/TiltSeries/TiltSeries.cs#L935-L938
`ImagePositions` come from `GridCTFDefocus` in `GetPositionInAllTilts()`
https://github.com/warpem/warp/blob/437508855b2a1c26858bc191d110fa3ad6b656cf/WarpLib/TiltSeries/TiltSeries.cs#L475


the defocus deltas will be zero in the absence of running ts_ctf
https://github.com/warpem/warp/blob/437508855b2a1c26858bc191d110fa3ad6b656cf/WarpLib/TiltSeries/TiltSeries.cs#L136-L141

This means your per tilt CTF won't change as it should throughout the volume, but the values should be roughly correct everywhere - I would play with a CTF simulator at your target defocus to get a sense for whether this difference is important for your use cases... 

this will affect your ability to do high res averaging though

**Comment by maurerv** [comment]
Hi,

I ran into what I believe to be the same issue today. 

I tried a couple of different versions, dev34 and dev35 in particular, all of which exited with a similar [console_log.txt](https://github.com/user-attachments/files/22648402/error_log.txt) and a logfile message  '10 seconds without heartbeat' (potentially linked to #420).

I backtracked the issue and found that the initial CTF grid search [`Parallel.For`](https://github.com/warpem/warp/blob/656a2d4ff1ed9ab9ecbd6b5cf9d27db8c134284a/WarpLib/TiltSeries/TiltSeries.ProcessCTFSimultaneous.cs#L307) consumes all CPU threads, starving the ASP.NET Core thread pool. This prevents heartbeat pulse HTTP requests from being processed. When pulses timeout after 5 seconds ([WorkerWrapper.cs:210](https://github.com/warpem/warp/blob/656a2d4ff1ed9ab9ecbd6b5cf9d27db8c134284a/WarpLib/WorkerWrapper.cs#L210)), an exception is raised, causing the WorkerWrapper heartbeat thread to die ([WorkerWrapper.cs:186](https://github.com/warpem/warp/blob/656a2d4ff1ed9ab9ecbd6b5cf9d27db8c134284a/WarpLib/WorkerWrapper.cs#L186)). The WarpWorker will notice the absence of heartbeats and shut itself down after a grace period of 10 seconds ([WarpWorker.cs:120](https://github.com/warpem/warp/blob/656a2d4ff1ed9ab9ecbd6b5cf9d27db8c134284a/WarpWorker/WarpWorker.cs#L120)). 

While `--fit_phase` triggers this fairly reliably due to the ~100x increase in grid search iterations, the underlying issue affects any sufficiently long computation.

This issue can be fixed by limiting the number of threads involved in the initial CTF grid search

```
// Leave threads for ASP.NET thread pool and internal framework tasks
int maxDegreeOfParallelism = Environment.ProcessorCount - 2;
var parallelOptions = new ParallelOptions { MaxDegreeOfParallelism = Math.Max(1, maxDegreeOfParallelism) };

Parallel.For(0, (int)((ZMax - ZMin + ZStep - 1e-6f) / ZStep), parallelOptions, zi =>
{
    float z = ZMin + zi * ZStep;
    [following](https://github.com/warpem/warp/blob/656a2d4ff1ed9ab9ecbd6b5cf9d27db8c134284a/WarpLib/TiltSeries/TiltSeries.ProcessCTFSimultaneous.cs#L310)
```

With that, I was able to successfully process my phase plate data :)

**Comment by alisterburt** [comment]
Wow - amazing work digging into this @maurerv, super impressed and thank you for taking the time!

This issue definitely crops up elsewhere and we likely need a proper solution rather than point solutions everywhere it may happen

@dtegunov i can't think of a general mechanism to keep one thread separate and not starved but I'm also on mobile and walking between buildings... is a solution obvious to you?!

**Comment by alisterburt** [comment]
potentially renting threads from a pool we manage rather than offloading that to the system? IIRC this is also good for perf in some situations - might already be done with the C# thread pool not sure

**Comment by dtegunov** [comment]
Thanks, @maurerv! How did you tie your WarpTools process to the ASP.NET threading pool? I thought that was only for ASP.NET processes. It would be weird if C#'s standard parallelization helpers were incompatible with it.

In any case, since you report this fixes the problem for you, I've hard-coded MaxDegreeOfParallelism to 8. It will be in the next dev version once I merge a bunch of other things.

**Comment by maurerv** [comment]
Hi @alisterburt and @dtegunov, thanks for addressing this.

I think the problem is not the thread pool itself. Plenty of threads are available in `System.Threading.ThreadPool` before/after entering `Parallel.For`. Its more likely an issue with CPU saturation/scheduling, which prevents Kestrel from processing the HTTP request in time. I am not a C# expert, but limiting MaxDegreeOfParallelism to leave resources for background tasks seems to be the least invasive approach.
