### ISSUE TITLE
1.10 to 2.0 migration

### ISSUE THREAD

**Issue by alisterburt** [warpem/warp#188]
this would enable people with data processed in 1.* to process on linux with 2.*

Not planned for the immediate future as of right now

**Comment by alisterburt** [comment]
Dimitry doesn't remember making any breaking changes so it's possible that `WarpTools move_data` is all that's required

**Comment by DrJesseHansen** [comment]
sorry for the late reply. 

Just trying this out now.  For the settings file I point to previous.settings from the warp job.   For the "--to" flag I point to the location of the raw frames, which is unchanged from the original settings file here since I'm not moving the frames.  for "--new_settings" (output folder for newly generated settings file) I have tried several locations but they all give this same error. I have also tried running this on different projects (in entirely unrelated folder locations).    
 
  
With the command below I get the following output.

```
WarpTools move_data --settings frames/previous.settings --to ./frames/ --new_settings ~/
Running command move_data with:
to = ./frames/
new_settings = (path)/jhansen/
settings = frames/previous.settings
input_data = {  }
input_data_recursive = False
input_processing = null
output_processing = null

Unhandled exception. System.UnauthorizedAccessException: Access to the path '(path)/jhansen/' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirError)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode, Boolean failForSymlink, Boolean& wasSymlink, Func`4 createOpenException)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, UnixFileMode openPermissions, Int64& fileLength, UnixFileMode& filePermissions, Boolean failForSymlink, Boolean& wasSymlink, Func`4 createOpenException)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.File.Create(String path)
   at Warp.OptionsWarp.Save(String path)
   at WarpTools.Commands.General.MoveData.Run(Object options) in (path)/WarpTools/Commands/General/MoveData.cs:line 37
   at WarpTools.WarpTools.Run(Object options) in (path)/WarpTools/Program.cs:line 30
   at Warp.Tools.CommandLineParserHelper.ParseAndRun(String[] args, Func`2 run, Type[] verbs, String appName)
   at WarpTools.WarpTools.Main(String[] args) in (path)/WarpTools/Program.cs:line 17
   at WarpTools.WarpTools.<Main>(String[] args)
Aborted
```

There seems to be nothing wrong with the folder permissions so I am not sure what to make of the permissions error.   For the --new_settings I tried giving it an output file name and now get a different error.  

```
WarpTools move_data --settings frames/previous.settings --to ./frames/ --new_settings ~/warp2.settings
Running command move_data with:
to = ./frames/
new_settings = (path)/jhansen/warp2.settings
settings = frames/previous.settings
input_data = {  }
input_data_recursive = False
input_processing = null
output_processing = null

No separate processing directory specified, turning off recursive search
No alternative input specified, will use input parameters from previous.settings
File search will be relative to (path)/frames
48 files found
Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'path2')
   at System.ArgumentNullException.Throw(String paramName)
   at System.IO.Path.Combine(String path1, String path2)
   at Warp.Tools.Helper.PathCombine(String[] paths)
   at WarpTools.Commands.BaseOptions.Evaluate() in (path)/WarpTools/Commands/BaseOptions.cs:line 145
   at WarpTools.Commands.General.MoveData.Run(Object options) in (path)/WarpTools/Commands/General/MoveData.cs:line 39
   at WarpTools.WarpTools.Run(Object options) in (path)/WarpTools/Program.cs:line 30
   at Warp.Tools.CommandLineParserHelper.ParseAndRun(String[] args, Func`2 run, Type[] verbs, String appName)
   at WarpTools.WarpTools.Main(String[] args) in (path)/WarpTools/Program.cs:line 17
   at WarpTools.WarpTools.<Main>(String[] args)
Aborted
```

**Comment by alisterburt** [comment]
@DrJesseHansen try
`WarpTools move_data --settings frames/previous.settings --to ./frames/ --new_settings fs.settings`

**Comment by DrJesseHansen** [comment]
@alisterburt thanks for the reply.    Same error, see below.  Note that I've truncated the full path length to (path).

```
WarpTools move_data --settings frames/previous.settings --to ./frames/ --new_settings fs.settings
Running command move_data with:
to = ./frames/
new_settings = fs.settings
settings = frames/previous.settings
input_data = {  }
input_data_recursive = False
input_processing = null
output_processing = null

No separate processing directory specified, turning off recursive search
No alternative input specified, will use input parameters from previous.settings
File search will be relative to (path)/frames
12828 files found
Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'path2')
   at System.ArgumentNullException.Throw(String paramName)
   at System.IO.Path.Combine(String path1, String path2)
   at Warp.Tools.Helper.PathCombine(String[] paths)
   at WarpTools.Commands.BaseOptions.Evaluate() in (path)/WarpTools/Commands/BaseOptions.cs:line 145
   at WarpTools.Commands.General.MoveData.Run(Object options) in (path)/WarpTools/Commands/General/MoveData.cs:line 39
   at WarpTools.WarpTools.Run(Object options) in (path)/WarpTools/Program.cs:line 30
   at Warp.Tools.CommandLineParserHelper.ParseAndRun(String[] args, Func`2 run, Type[] verbs, String appName)
   at WarpTools.WarpTools.Main(String[] args) in (path)/WarpTools/Program.cs:line 17
   at WarpTools.WarpTools.<Main>(String[] args)
Aborted

```

**Comment by alisterburt** [comment]
try running from within the data dir and changing paths?

**Comment by DrJesseHansen** [comment]
I just noticed that despite throwing the error about path2 it does in fact spit out a file as expected.  I went ahead and tried using that file as input for subsequent steps. I could indeed create the source (could not before) but it throw quite a few errors:

```
Running command create_source with:
population = m/batch07.population
processing_settings = fs.settings
name = batch07
nframes = 
files = 

Looking for data... found 48 files
Loading metadata... System.Exception: Expected 4 floats
   at Warp.Tools.XMLHelper.LoadAttribute(XPathNavigator nav, String name, Matrix2 defaultValue)
System.Exception: Expected 4 floats
   at Warp.Tools.XMLHelper.LoadAttribute(XPathNavigator nav, String name, Matrix2 defaultValue)
System.Exception: Expected 4 floats
   at Warp.Tools.XMLHelper.LoadAttribute(XPathNavigator nav, String name, Matrix2 defaultValue)
System.Exception: Expected 4 floats
   at Warp.Tools.XMLHelper.LoadAttribute(XPathNavigator nav, String name, Matrix2 defaultValue)

**(continues to repeat the "4 floats" error about 3000 times).** 

Done
Data source created: (path)/frames/batch07.source
```

I went ahead and ran MCore with 0 iterations to test and that seemed to run until almost completion then got the error below.  Note that I've tried this with multiple compute nodes and each gives the same error.  

Probably quite tricky to track down the cause of this so I'm willing to admit defeat, was just hoping I could import the win WARP session but I'll survive if not.  

For completeness would you like that I post this on the forum as well since you had written "let us know how it goes if you try this out"?

thanks again for your time and help! 

Jesse


```
46/48Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.                       
   at Warp.Tools.IOHelper.ReadMapFloat(System.String, Warp.Tools.int2, Int64, System.Type, Boolean, Int32[], System.IO.Stream, Single[][])
   at Warp.Tools.IOHelper.ReadMapFloat(System.String, Warp.Tools.int2, Int64, System.Type, Int32[], System.IO.Stream, Single[][])
   at Warp.Tools.IOHelper.ReadMapFloatPatient(Int32, Int32, System.String, Warp.Tools.int2, Int64, System.Type, Int32[], System.IO.Stream, Single[][])
   at Warp.TiltSeries.LoadMovieData(Warp.ProcessingOptionsBase, Warp.Movie[] ByRef, Warp.Image[] ByRef, Boolean, Warp.Image[] ByRef, Warp.Image[] ByRef, Boolean)
   at Warp.TiltSeries+<>c__DisplayClass100_0.<PerformMultiParticleRefinement>b__4()
   at Warp.TiltSeries.PerformMultiParticleRefinement(System.String, Warp.ProcessingOptionsMPARefine, Warp.Sociology.Species[], Warp.Sociology.DataSource, Warp.Image, Warp.Tools.DefectModel, System.Action`1<System.String>)
   at WarpWorker.WarpWorker.EvaluateCommand(Warp.Tools.NamedSerializableObject)
   at WarpWorker.API.ServiceController.EvaluateCommand()
   at DynamicClass.lambda_method4(System.Runtime.CompilerServices.Closure, System.Object, System.Object[])
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State ByRef, Scope ByRef, System.Object ByRef, Boolean ByRef)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State ByRef, Scope ByRef, System.Object ByRef, Boolean ByRef)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State ByRef, Scope ByRef, System.Object ByRef, Boolean ByRef)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Filters.ControllerActionFilter.OnActionExecutionAsync(Microsoft.AspNetCore.Mvc.Filters.ActionExecutingContext, Microsoft.AspNetCore.Mvc.Filters.ActionExecutionDelegate)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State ByRef, Scope ByRef, System.Object ByRef, Boolean ByRef)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State ByRef, Scope ByRef, System.Object ByRef, Boolean ByRef)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Mvc.Routing.ControllerRequestDelegateFactory+<>c__DisplayClass12_0.<CreateRequestDelegate>b__0(Microsoft.AspNetCore.Http.HttpContext)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.Invoke(Microsoft.AspNetCore.Http.HttpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware+<Invoke>d__5.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware+<Invoke>d__5, Swashbuckle.AspNetCore.SwaggerUI, Version=6.5.0.0, Culture=neutral, PublicKeyToken=4232c99127b3c254]](<Invoke>d__5 ByRef)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware+<Invoke>d__4.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware+<Invoke>d__4, Swashbuckle.AspNetCore.Swagger, Version=6.5.0.0, Culture=neutral, PublicKeyToken=62657d7474907593]](<Invoke>d__4 ByRef)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(Microsoft.AspNetCore.Http.HttpContext, Swashbuckle.AspNetCore.Swagger.ISwaggerProvider)
   at Microsoft.AspNetCore.HostFiltering.HostFilteringMiddleware.Invoke(Microsoft.AspNetCore.Http.HttpContext)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol+<ProcessRequests>d__238`1[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(System.Threading.Thread, System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol+<ProcessRequests>d__238`1[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], Microsoft.AspNetCore.Server.Kestrel.Core, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].MoveNext(System.Threading.Thread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool+WorkerThread.WorkerThreadStart()
Unhandled exception. System.NotImplementedException: The method or operation is not implemented.
   at MCore.MCore.WorkerDied(Object sender, EventArgs e) in (path)/warp/MCore/MCore.cs:line 597
   at Warp.WorkerWrapper.ReportDeath()
   at Warp.WorkerWrapper.<StartHeartbeat>b__14_0()
./04_check.sh: line 3: 161513 Aborted                 MCore --population m/batch07.population --iter 0

```

**Comment by alisterburt** [comment]
@DrJesseHansen the error about `path2` is indicating that some file it was expecting to find wasn't found - you'll have to troubleshoot that a bit more for it to have any chance of working

**Comment by DrJesseHansen** [comment]
I have found the source of one problem.   In the windows version the previous.settings parameter name was "Folder" while in the linux version it's "DataFolder".  So I change the param name to DataFolder and it seems to have worked.   Also I needed to change the slashes from "\" (windows) to "/" linux.  Now the move_data command runs without issue.  Nice!

However, running the Mtools create_source still gives the error above about "expected 4 floats".  Will try to figure this one out...

**Comment by alisterburt** [comment]
Great work!
