### ISSUE TITLE
system.NotImplementedException: the method or operation is not implemented

### ISSUE THREAD

**Issue by DrJesseHansen** [warpem/warp#237]
Hi,

I am using Warp warptools/2.0.0dev26. I am using 4x 2080Ti cards with 100GB CPU memory. 

I am running the command below:

MCore \
--population m/MyPrOtEiN.population \
--iter 0

It runs through the majority of the dataset then crashes with the error below.  I run it again and it crashes at a different position, making me think it's not the data..

```
Loading population... Done
Creating directories... Done
Spawning workers... Done
Preparing for refinement \ufffd\ufffd\ufffd this will take a few minutes per species
Preparing refinement requisites...
1/1                                                                           
Performing refinement
Preparing population for data source MyPrOtEiN...Done
Loading gain reference for MyPrOtEiN... Done
Refining all series in data source...
203/350Unhandled exception. Unhandled exception. System.NotImplementedException: The method or operation is not implemented.
   at MCore.MCore.WorkerDied(Object sender, EventArgs e) in (path)/warp/MCore/MCore.cs:line 597
   at Warp.WorkerWrapper.ReportDeath() in (path)/warp/WarpLib/WorkerWrapper.cs:line 255
   at Warp.WorkerWrapper.<StartHeartbeat>b__14_0() in (path)/warp/WarpLib/WorkerWrapper.cs:line 189
./11_Mcore.job: line 3: 2917798 Aborted                 MCore --population m/MyPrOtEiN.population --iter 0
```

Jesse

**Comment by alisterburt** [comment]
I got an email with this but the comment appears to have disappeared - 
```txt
System.DllNotFoundException: Unable to load shared library 'LibTorchSharp' or one of its dependencies. In order to help diagnose loading problems, consider using a tool like strace. If you're using glibc, consider setting the LD_DEBUG environment variable: 
/nfs/scistore07/clustersw/debian/bookworm/warp/2.0.0dev25/linux-x64/publish/LibTorchSharp.so: cannot open shared object file: No such file or directory
libtorch.so: cannot open shared object file: No such file or directory
libLibTorchSharp.so: cannot open shared object file: No such file or directory
/nfs/scistore07/clustersw/debian/bookworm/warp/2.0.0dev25/linux-x64/publish/LibTorchSharp: cannot open shared object file: No such file or directory
/nfs/scistore07/clustersw/debian/bookworm/warp/2.0.0dev25/linux-x64/publish/libLibTorchSharp: cannot open shared object file: No such file or directory

   at TorchSharp.NN.Modules.THSNN_UNet3D_ctor(Int64 depth_block, Int64 width_block, Int64 max_width, Int64 input_channels, Int64 final_channels, Boolean residual_u, Boolean usegroupnorm, Boolean progressivedepth, IntPtr& pBoxedModule)
   at TorchSharp.NN.Modules.UNet3D(Int64 depth_block, Int64 width_block, Int64 max_width, Int64 input_channels, Int64 final_channels, Boolean residual_u, Boolean usegroupnorm, Boolean progressivedepth) in /warp/TorchSharp/NN/UNet3D.cs:line 29
   at Warp.NoiseNet3DTorch.<.ctor>b__23_0(Int32 i, Int32 threadID) in /warp/WarpLib/NNModels/NoiseNet3DTorch.cs:line 81
   at Warp.Tools.Helper.ForCPU(Int32 fromInclusive, Int32 toExclusive, Int32 nThreads, Action`1 funcSetup, Action`2 funcIterator, Action`1 funcTeardown) in /warp/WarpLib/Tools/Helper.cs:line 736
   at Warp.NoiseNet3DTorch..ctor(int3 boxDimensions, Int32[] devices, Int32 batchSize, Int32 depth, Boolean progressiveDepth, Int32 maxWidth) in /warp/WarpLib/NNModels/NoiseNet3DTorch.cs:line 77
   at Warp.Sociology.Species.PrepareRefinementRequisites(Boolean makeRefs, Int32 singleGPU, String stagingSave, String stagingLoad) in 
/warp/WarpLib/Sociology/Species.cs:line 1884
   at WarpWorker.WarpWorker.EvaluateCommand(NamedSerializableObject Command) in //warp/WarpWorker/WarpWorker.cs:line 687
```

This library is built as part of the Warp build process and comes with the conda install - something about your environment is misconfigured so that the library can no longer be found. Did you overwrite LD_LIBRARY_PATH?

**Comment by alisterburt** [comment]
although the above error looks like a different error than the one you originally reported...

**Comment by DrJesseHansen** [comment]
I figured out that running with 1 GPU did not give the error.  Earlier I was running with 4 GPUs.  Have noticed that for some reason I run into issues when running in parallel, not sure why...

**Comment by alisterburt** [comment]
Is the error reproducible when you run with multiple GPUs? We have recently fixed a few errors specific to multi-species, multi-gpu. I'll close here for now but if you can reproduce on `2.00dev26` then please reopen so we can investigate further

**Comment by DrJesseHansen** [comment]
Installed the latest commit and the problem persists.  It now runs through to the end and throws the error rather than doing it mid-run, so looks like some multi-gpu issues were resolved.  Not sure why though it's happening at the end of the run, and why there is no worker file.

**Comment by alisterburt** [comment]
tracking in #266
