### ISSUE TITLE
Minor bug: MTools create data source - Must be in the folder where the settings file is.

### ISSUE THREAD

**Issue by rkjensen** [warpem/warp#312]
When creating a new data source for an M project you must be in the folder where you have your tilt series settings file, at least if the DataFolder is given as a relative path in the settings file.

As you can see in the below command and accompanying run log, it searches relative to the current folder.

```
pwd
/scratch/kjeldsen/warp_runs/untreated_02/merge_test/merge_all/m/c1

MTools create_source -p test.population -s ../../warp_tiltseries.settings -n test
Running command create_source with:
population = test.population
processing_settings = ../../warp_tiltseries.settings
name = test
nframes = 
files = 

Looking for data... Unhandled exception. System.IO.DirectoryNotFoundException: Could not find a part of the path '/scratch/kjeldsen/warp_runs/untreated_02/merge_test/merge_all/m/c1/tomostar'.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerableFactory.UserFiles(String directory, String expression, EnumerationOptions options)
   at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at MTools.Commands.CreateSource.Run(Object options)
   at MTools.MTools.Run(Object options)
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at MTools.MTools.Main(String[] args)
Aborted (core dumped)
```

**Comment by alisterburt** [comment]
thanks for the report @rkjensen !
