### ISSUE TITLE
Noise2Mic --help tries to prepare data

### ISSUE THREAD

**Issue by cdienem** [warpem/warp#6]
When running 
```
Noise2Mic --help
```

the executable should only print the help but it additionally tries to handle some data and gives the output:
```
Noise2Mic 2.0.0+201d90fcb0538ede96cf7cf9dffeb53b23ce6235
Copyright (C) 2024 Noise2Mic

  --processingdir          Required. Relative path to a the root folder used during Warp's processing,
                           i.e. where the XML metadata are.

  --start_model            (Default: ) Name of the file with the initial (pre-trained) model.

  --old_model              (Default: ) Name of the folder with the pre-trained model. Leave empty to
                           train a new one.

  --learningrate_start     (Default: 0.0001) Initial learning rate that will be decreased exponentially
                           to reach the final learning rate.

  --learningrate_finish    (Default: 1E-06) Final learning rate, after exponential decrease from the
                           initial rate.

  --dont_augment           (Default: false) Don't augment data through random rotations. Only rotations
                           by multiples of 180 degrees will be used.

  --rescale_angpix         (Default: -1) Pixel size to scale the micrographs to during training and
                           denoising.

  --lowpass                (Default: -1) Low-pass filter to be applied to denoised micrographs (in
                           Angstroms).

  --iterations             (Default: 600) Number of iterations.

  --window                 (Default: 512) Size of the model's input window in pixels; should be a
                           multiple of 256.

  --batchsize              (Default: 64) Batch size for model training. Decrease if you run out of
                           memory. The number of iterations will be adjusted automatically.

  --gpuid_network          (Default: 0) GPU ID used for network training.

  --gpuid_preprocess       (Default: 1) GPU ID used for data preprocessing. Ideally not the GPU used for
                           training

  --help                   Display this help screen.

  --version                Display version information.

Preparing data:
Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'path2')
   at System.ArgumentNullException.Throw(String paramName)
   at System.IO.Path.Combine(String path1, String path2)
   at Noise2Mic.Noise2Mic.Main(String[] args) in /opt/warp/warp-2.0.0dev1/Noise2Mic/Noise2Mic.cs:line 64
Aborted (core dumped)
```

**Comment by alisterburt** [comment]
Thank you @cdienem for the report! Will get a fix pushed out next time I'm at the computer 🙂
